export { default as Header } from "./header"
export { default as Layout } from "./layout"
export { default as SEO } from "./seo"
export { default as Image } from "./image"
export { default as Jumbo } from './jumbo'  
export { default  as Jumbo2 } from './jumbo_2';
export { default as Product } from './products'
export { default as ProductDetail } from './productDetail';
export { default as Stars } from './Stars';
export { default as Cart } from './Cart';